AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for cross-account admin support access from Taimos'
Resources:
  SupportRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: TaimosSupport
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::292004443359:root'
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:
  RoleARN:
    Description: 'The ARN of the support role; Please send this to Taimos support'
    Value: !GetAtt SupportRole.Arn